GET http://localhost:5001/api/v1/user/sss
###

POST  http://localhost:5001/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###

POST  http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###

GET http://localhost:5001/api/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjcxMzM5MjIzLCJleHAiOjE2NzEzMzkyODN9.wEvfvKyOv_myndu9XR6pe1GtZ_6tH4c__LWMLRiKET4
###

GET  http://localhost:5001/api/v1/insert/
Content-Type: application/json
###

# GET  http://localhost:5001/api/v1/book/?order[]=price&order[]=DESC&limit=2&page=2&name=of
# GET  http://localhost:5001/api/v1/book/?available[]=5&available[]=10
GET  http://localhost:5001/api/v1/book/